[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["Bas Dam <bas@🚀.kz>"]
description = ""
name = "Linked List Kata"
version = "0.1.0"
[tool.poetry.dependencies]
pytest = "^6.2.4"
python = "^3.8"
[tool.poetry.dev-dependencies]
